return {}
-- return {
--   {
--     "neovim/nvim-lspconfig",
--     opts = {
--       servers = {
--         pyright = {
--           mason = false,
--         },
--         ruff_lsp = {
--           mason = false,
--         },
--       },
--     },
--   },
-- }
