return {
  "folke/which-key.nvim",
  -- event = function(_, event)
  --   return { "VeryLazy" }
  -- end,
  keys = { "<Leader>" },
  opts = {
    preset = "classic",
    icons = {
      mappings = false,
    },
    delay = 0,
    plugins = { spelling = false },
    spec = {
      { "<leader>b", group = "buffers", mode = { "n", "v", "x" } }, -- remmaped default spec to disable dynamic buffers
      { "<leader>a", group = "ai", mode = { "n", "v", "x" } },
      { "<leader>r", group = "refactor" },
      { "<leader>k", group = "kubernetes" },
      { "<leader>n", group = "noice" },
      { "<leader>L", group = "lazy" },
      { "<leader>S", group = "scissors", mode = { "n", "v", "x" } },
      { "<leader>tg", group = "ray-x go" },
      { "<leader>cg", group = "go" },
      { "<leader>cp", group = "python" },
      { "<leader>gM", group = "merge" },
      { "<leader>gh", group = "hunks" },
      { "<leader>fi", group = "find ignore" },
      { "<leader>wS", group = "setup workspaces" },
      { "<leader>fo", group = "open in" },
      { "<leader>fy", group = "yank" },
      { "<leader>si", group = "infra" },
      { "<leader>ct", group = "terraform" },
      { "<leader>ctw", group = "workspace" },
      { "<leader>cm", group = "metals" },
      { "<leader>cL", group = "LSP" },
      { "<leader>bd", group = "docker" },
      { "<leader>2", hidden = true },
      { "<leader>3", hidden = true },
      { "<leader>4", hidden = true },
      { "<leader>5", hidden = true },
      { "<leader>wT", hidden = true },
      { "<leader>ua", hidden = true },
      { "<leader>ug", hidden = true },
      { "<leader>ui", hidden = true },
      { "<leader>uI", hidden = true },
      { "<leader>uI", hidden = true },
      { "<leader>uG", hidden = true },
      { "<leader>uA", hidden = true },
      { "<leader>uS", hidden = true },
      { "<leader>dp", hidden = true },
      { "<leader>wm", hidden = true },
    },
  },
}
